name: Build master - $(Build.BuildId)

trigger:
  branches:
    include:
    - master

stages:
- stage: Build
  jobs:
  - job: Linux
    pool:
      vmImage: ubuntu-latest
    variables:
      CACHE_FOLDER: $(Pipeline.Workspace)/cache
      ESY__CACHE_INSTALL_PATH: /home/vsts/.esy/3_____________________________________________________________________/i
    steps:
    - template: .ci/build-platform.yml
      parameters:
        installFolderPath: "/3______________________________________________________________/i"
    - template: .ci/utils/prepare-cache.yml

  - job: macOS
    pool:
      vmImage: macOS-latest
    variables:
      CACHE_FOLDER: $(Pipeline.Workspace)/cache
      ESY__CACHE_INSTALL_PATH: /Users/vsts/.esy/3____________________________________________________________________/i
    steps:
    - template: .ci/build-platform.yml
    - template: .ci/utils/prepare-cache.yml
      parameters:
        installFolderPath: "/3_______________________________________________/i"

  # - job: Windows
  #   pool:
  #     vmImage: windows-latest
  #   variables:
  #     ESY__PREFIX: $(Pipeline.Workspace)\.esy
  #   steps:
  #   - template: .ci/build-platform.yml
  #     parameters:
  #       esyLockPath: $(Build.SourcesDirectory)\esy.lock\index.json
  #       installFolderPath: \3_
