name: Publish packages to npm

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
          ref: ${{ github.ref }}
          submodules: true
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: Install esy
        run: npm install -g esy
      - name: Publish packages
        run: |
          set -e
          packages=(
              morph
              morph_base
              morph_graphql_server
              morph_server_base
              morph_server_http
              morph_server_https
          )
          extract() {
          # Field's key/value should be on their own line
          echo $(cat package.json \
              | grep "$1" \
              | head -1 \
              | awk -F: '{ print $2 }' \
              | sed 's/[",]//g')
          }

          for name in "${packages[@]}"
          do
          cp $name.json $name/package.json
          package_name=$(extract name)
          version=$(extract version)
          npm_version=$(npm view "$package_name" version 2> /dev/null || echo 0)
          if [ "$npm_version" != "$version" ]
          then
              cp -r LICENSE $name/LICENSE
              cp -r README.md $name/README.md
              cp -r $name.opam $name/$name.opam
              cd $name
              esy
              npm publish --access public
              cd ..
              git clean -f -d ./$name
          fi
          done
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
